apiVersion: apps/v1
kind: Deployment
metadata:
  name: balancereader
  namespace: balancereader
spec:
  selector:
    matchLabels:
      app: balancereader
  template: 
    spec: 
      containers:
      - name: balancereader
        image: gcr.io/arun-krm/cymbal-bank/release/balancereader:ea51e42
        env:
        - name: ENABLE_TRACING
          value: "true"
        - name: ENABLE_METRICS
          value: "true"
        - name: LOG_LEVEL
          value: "info"