apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerwriter
  namespace: ledgerwriter
spec:
  selector:
    matchLabels:
      app: ledgerwriter
  template: 
    spec: 
      containers:
      - name: ledgerwriter
        image: gcr.io/arun-krm/cymbal-bank/release/ledgerwriter:5cdce8e
        env:
        - name: ENABLE_TRACING
          value: "true"
        - name: ENABLE_METRICS
          value: "true"
        - name: LOG_LEVEL
          value: "info"